### ISSUE TITLE
Add Techdocs page for each of the apps

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius-kubernetes#398]
Example page: https://github.com/ortelius/ortelius-kubernetes/blob/main/docs/argocd.md

**Comment by itisaby** [comment]
After creating all the techdocs,
Do I need to add them in the mkdocs.yml file as well ?

**Comment by bradmccoydev** [comment]
yes please add them to mkdocs.yml also @itisaby

**Comment by itisaby** [comment]
Cool I am on it

**Comment by itisaby** [comment]
I have added the PR - https://github.com/ortelius/ortelius-kubernetes/pull/402

**Comment by bradmccoydev** [comment]
Nice work @itisaby
