### ISSUE TITLE
Create Github action to publish techdocs to Azure Storage

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius-kubernetes#399]
This action is to publish techdocs to our azure storage account that we setup in azure-infra repo.

It must loop through the components. So we can comment on the design in this ticket. 

Let me know once you investigate what auth you need me to provide.

**Comment by itisaby** [comment]
These are the following things I need to configure the actions 
- TECHDOCS_CONTAINER_NAME
- TECHDOCS_STORAGE_ACCOUNT
- AZURE_SUBSCRIPTION_ID
- AZURE_TENANT_ID
- AZURE_CLIENT_ID
- AZURE_CLIENT_SECRET
This is the command I will use to publish into Azure Storage using GitHub Actions rest steps will be the same as given in the docs of Backstage 
` techdocs-cli publish --publisher-type azureBlobStorage --azureAccountName $TECHDOCS_STORAGE_ACCOUNT --storage-name $TECHDOCS_CONTAINER_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME`

**Comment by bradmccoydev** [comment]
ok i can put the following into the github actions secrets:
AZURE_SUBSCRIPTION_ID
AZURE_TENANT_ID
AZURE_CLIENT_ID
AZURE_CLIENT_SECRET

and you made these in terraform so you know:
TECHDOCS_CONTAINER_NAME
TECHDOCS_STORAGE_ACCOUNT

**Comment by itisaby** [comment]
Yes

**Comment by itisaby** [comment]
Are the secrets added? 
I am all set to raise a PR, I wrote the actions, but we also need to update the [app-config.yaml](https://github.com/ortelius/backstage/blob/main/app-config.yaml) to build the techdocs which will be shown in the backstage.

**Comment by bradmccoydev** [comment]
Lets move that work to the azure-infra repo as discussed as the secrets are already there

**Comment by bradmccoydev** [comment]
one day i will make the secrets global across the repos with small access to azure
