### ISSUE TITLE
Update Backstage Techdocs config for Azure

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius-kubernetes#403]
Depends on issue #399 

After Docs are pushing to Azure Storage account we need to update the Config for techdocs.

ortelius-kubernetes/kube-infra/kustomize/catalog/backstage/base/kustomization.yaml

Line: 119 down.

Any access requirements we can give in Terraform in Azure-infra repo
We will also need to update the backstage repo ortelius/backstage that contains the config-production.yaml file

**Comment by itisaby** [comment]
#405 I have converted into AWS S3. Techdocs will be created and published into the AWS S3 bucket.

**Comment by bradmccoydev** [comment]
I will add the config for this tomorrow

**Comment by itisaby** [comment]
Is it done?
